completely updated wordpress_download function

diff --git a/easy_wordpress b/easy_wordpress
--- a/easy_wordpress
+++ b/easy_wordpress
@@ -170,28 +170,54 @@ function set_nginx_config
 	return 0
 }
 
+#function download_wordpress
+#{
+#	home=$1
+#	
+#	echo "Downloading Wordpress........."
+#	#download wordpress 
+#	#tar has better option of no-stripping
+#	sudo wget -P $home/$dom/htdocs/ http://wordpress.org/latest.zip || (echo "Failed to download Wordpress..." && exit)
+#	
+#	#added - on server if unzip is not installed then script will install unzip...
+#	hash unzip &> /dev/null
+#        if [ $? -ne 0 ];then
+#		echo "The program unzip is currently not installed."
+#	        sudo apt-get install unzip || (echo "Failed to install unzip" && exit)
+#	fi
+#	sudo unzip $home/$dom/htdocs/latest.zip -d $home/$dom/htdocs/ || (echo "Unzipping opertaion failed..." && exit)
+#	
+#	#Doing similar to --strip-components=1 used in tar....Removing wordpress directory
+#	sudo mv $home/$dom/htdocs/wordpress/* $home/$dom/htdocs/ || (echo "Failed to move...no such file or directory" && exit)
+#	sudo rm -rf $home/$dom/htdocs/wordpress/
+#	sudo rm $home/$dom/htdocs/latest.zip
+#	return 0
+#}
 
 function download_wordpress
 {
-	home=$1
-	
-	echo "Downloading Wordpress........."
-	#download wordpress 
-	#tar has better option of no-stripping
-	sudo wget -P $home/$dom/htdocs/ http://wordpress.org/latest.zip || (echo "Failed to download Wordpress..." && exit)
-	
-	#added - on server if unzip is not installed then script will install unzip...
-	hash unzip &> /dev/null
-        if [ $? -ne 0 ];then
-		echo "The program unzip is currently not installed."
-	        sudo apt-get install unzip || (echo "Failed to install unzip" && exit)
-	fi
-	sudo unzip $home/$dom/htdocs/latest.zip -d $home/$dom/htdocs/ || (echo "Unzipping opertaion failed..." && exit)
-	
-	#Doing similar to --strip-components=1 used in tar....Removing wordpress directory
-	sudo mv $home/$dom/htdocs/wordpress/* $home/$dom/htdocs/ || (echo "Failed to move...no such file or directory" && exit)
-	sudo rm -rf $home/$dom/htdocs/wordpress/
-	sudo rm $home/$dom/htdocs/latest.zip
+      	#For the first site on linux machine, script will download wordpress 
+      	#For second site, script will copy wordpress from cache to site's home directory
+      	home=$1
+      	sudo mkdir -p /var/cache/easy_wp
+	cache=/var/cache/easy_wp  
+        
+        if [ ! -f $cache/latest.zip ];then
+                echo "Not found in cache..."
+                echo "Downloading wordpress"
+                sudo wget -P $cache http://wordpress.org/latest.zip || (echo "Failed to download Wordpress..." && exit)
+
+                hash unzip &> /dev/null
+                if [ $? -ne 0 ];then
+                        echo "The program unzip is currently not installed."
+                        sudo apt-get install unzip || echo "Failed to install unzip" && exit
+                fi
+                sudo unzip $cache/latest.zip -d $cache || (echo "Unzipping opertaion failed..." && exit)
+        fi
+
+        #once $cache has latest.zip and wordpress dir ....then proceed for copying it to...$nginx_home
+        echo "Copying wordpress from cache..."
+        sudo cp -r $cache/wordpress/* $nginx_home || (echo "Failed to copy " && exit)
 	return 0
 }
 
